name: SonarCloud

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Required to get a proper git history for SonarCloud analysis

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          cd src
          pytest --cov=./ --cov-report=xml 


      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for SonarCloud automatic analysis
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SONAR_TOKEN is the secret you should create in your repo settings

