name: SonarCloud

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      
      - name: Install Dependencies
        run: |
          pip3 install pytest pytest-mock pytest-cov
          
      - name: Run tests with coverage
        run: pytest --cov=./ --cov-report=xml
        env:
          TABLE_NAME: DONTCARE
        working-directory: .

      - name: Fix coverage paths
        run: |
          sed -i 's|/home/runner/work/sc-test/sc-test|.|g' coverage.xml
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SONAR_TOKEN is the secret you should create in your repo settings

